
auth.token=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

defaults.org=artechspirit
defaults.project=react-native

defaults.url=https://sentry.io/
